DROP TABLE manager_auth IF EXISTS;
DROP TABLE foods IF EXISTS;
DROP TABLE managers IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE managers
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name             VARCHAR(255)            NOT NULL,
    email            VARCHAR(255)            NOT NULL,
    password         VARCHAR(255)            NOT NULL,
    registered       TIMESTAMP DEFAULT now() NOT NULL,
    enabled          BOOLEAN   DEFAULT TRUE  NOT NULL,
    calories_per_day INTEGER   DEFAULT 2000  NOT NULL
);
CREATE UNIQUE INDEX managers_unique_email_idx
    ON MANAGERS (email);

CREATE TABLE manager_auth
(
    manager_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT manager_roles_idx UNIQUE (manager_id, role),
    FOREIGN KEY (manager_id) REFERENCES MANAGERS (id) ON DELETE CASCADE
);

CREATE TABLE foods
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    date_time   TIMESTAMP    NOT NULL,
    description VARCHAR(255) NOT NULL,
    calories    INT          NOT NULL,
    manager_id     INTEGER      NOT NULL,
    FOREIGN KEY (manager_id) REFERENCES MANAGERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX foods_unique_manager_datetime_idx
    ON foods (manager_id, date_time)